[build]
target = "x86_64-unknown-none"
[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = "-Crelocation-model=static -Clink-args=-Tbootboot.ld -Ccode-model=kernel --emit=asm --extern core=/home/runner/Os/libcore/libcore.rlib"
